// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Location.proto

package com.tiza.rpc.bean;

public final class LocationBean {
  private LocationBean() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface LocationOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required double elng = 1;
    /**
     * <code>required double elng = 1;</code>
     */
    boolean hasElng();
    /**
     * <code>required double elng = 1;</code>
     */
    double getElng();

    // required double elat = 2;
    /**
     * <code>required double elat = 2;</code>
     */
    boolean hasElat();
    /**
     * <code>required double elat = 2;</code>
     */
    double getElat();

    // optional string province = 3;
    /**
     * <code>optional string province = 3;</code>
     */
    boolean hasProvince();
    /**
     * <code>optional string province = 3;</code>
     */
    String getProvince();
    /**
     * <code>optional string province = 3;</code>
     */
    com.google.protobuf.ByteString
        getProvinceBytes();

    // optional string city = 4;
    /**
     * <code>optional string city = 4;</code>
     */
    boolean hasCity();
    /**
     * <code>optional string city = 4;</code>
     */
    String getCity();
    /**
     * <code>optional string city = 4;</code>
     */
    com.google.protobuf.ByteString
        getCityBytes();

    // optional string area = 5;
    /**
     * <code>optional string area = 5;</code>
     */
    boolean hasArea();
    /**
     * <code>optional string area = 5;</code>
     */
    String getArea();
    /**
     * <code>optional string area = 5;</code>
     */
    com.google.protobuf.ByteString
        getAreaBytes();
  }
  /**
   * Protobuf type {@code Location}
   */
  public static final class Location extends
      com.google.protobuf.GeneratedMessage
      implements LocationOrBuilder {
    // Use Location.newBuilder() to construct.
    private Location(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Location(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Location defaultInstance;
    public static Location getDefaultInstance() {
      return defaultInstance;
    }

    public Location getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Location(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 9: {
              bitField0_ |= 0x00000001;
              elng_ = input.readDouble();
              break;
            }
            case 17: {
              bitField0_ |= 0x00000002;
              elat_ = input.readDouble();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              province_ = input.readBytes();
              break;
            }
            case 34: {
              bitField0_ |= 0x00000008;
              city_ = input.readBytes();
              break;
            }
            case 42: {
              bitField0_ |= 0x00000010;
              area_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return LocationBean.internal_static_Location_descriptor;
    }

    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return LocationBean.internal_static_Location_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Location.class, Builder.class);
    }

    public static final com.google.protobuf.Parser<Location> PARSER =
        new com.google.protobuf.AbstractParser<Location>() {
      public Location parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Location(input, extensionRegistry);
      }
    };

    @Override
    public com.google.protobuf.Parser<Location> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required double elng = 1;
    public static final int ELNG_FIELD_NUMBER = 1;
    private double elng_;
    /**
     * <code>required double elng = 1;</code>
     */
    public boolean hasElng() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required double elng = 1;</code>
     */
    public double getElng() {
      return elng_;
    }

    // required double elat = 2;
    public static final int ELAT_FIELD_NUMBER = 2;
    private double elat_;
    /**
     * <code>required double elat = 2;</code>
     */
    public boolean hasElat() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required double elat = 2;</code>
     */
    public double getElat() {
      return elat_;
    }

    // optional string province = 3;
    public static final int PROVINCE_FIELD_NUMBER = 3;
    private Object province_;
    /**
     * <code>optional string province = 3;</code>
     */
    public boolean hasProvince() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional string province = 3;</code>
     */
    public String getProvince() {
      Object ref = province_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          province_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string province = 3;</code>
     */
    public com.google.protobuf.ByteString
        getProvinceBytes() {
      Object ref = province_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        province_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string city = 4;
    public static final int CITY_FIELD_NUMBER = 4;
    private Object city_;
    /**
     * <code>optional string city = 4;</code>
     */
    public boolean hasCity() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional string city = 4;</code>
     */
    public String getCity() {
      Object ref = city_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          city_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string city = 4;</code>
     */
    public com.google.protobuf.ByteString
        getCityBytes() {
      Object ref = city_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        city_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional string area = 5;
    public static final int AREA_FIELD_NUMBER = 5;
    private Object area_;
    /**
     * <code>optional string area = 5;</code>
     */
    public boolean hasArea() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional string area = 5;</code>
     */
    public String getArea() {
      Object ref = area_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          area_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string area = 5;</code>
     */
    public com.google.protobuf.ByteString
        getAreaBytes() {
      Object ref = area_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        area_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private void initFields() {
      elng_ = 0D;
      elat_ = 0D;
      province_ = "";
      city_ = "";
      area_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasElng()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasElat()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeDouble(1, elng_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeDouble(2, elat_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getProvinceBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeBytes(4, getCityBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBytes(5, getAreaBytes());
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(1, elng_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(2, elat_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getProvinceBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(4, getCityBytes());
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(5, getAreaBytes());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @Override
    protected Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static Location parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Location parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Location parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Location parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Location parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static Location parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static Location parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static Location parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static Location parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static Location parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(Location prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Location}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements LocationOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return LocationBean.internal_static_Location_descriptor;
      }

      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return LocationBean.internal_static_Location_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Location.class, Builder.class);
      }

      // Construct using com.tiza.rpc.bean.LocationBean.Location.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        elng_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000001);
        elat_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000002);
        province_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        city_ = "";
        bitField0_ = (bitField0_ & ~0x00000008);
        area_ = "";
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return LocationBean.internal_static_Location_descriptor;
      }

      public Location getDefaultInstanceForType() {
        return Location.getDefaultInstance();
      }

      public Location build() {
        Location result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public Location buildPartial() {
        Location result = new Location(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.elng_ = elng_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.elat_ = elat_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.province_ = province_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.city_ = city_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.area_ = area_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Location) {
          return mergeFrom((Location)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Location other) {
        if (other == Location.getDefaultInstance()) return this;
        if (other.hasElng()) {
          setElng(other.getElng());
        }
        if (other.hasElat()) {
          setElat(other.getElat());
        }
        if (other.hasProvince()) {
          bitField0_ |= 0x00000004;
          province_ = other.province_;
          onChanged();
        }
        if (other.hasCity()) {
          bitField0_ |= 0x00000008;
          city_ = other.city_;
          onChanged();
        }
        if (other.hasArea()) {
          bitField0_ |= 0x00000010;
          area_ = other.area_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasElng()) {
          
          return false;
        }
        if (!hasElat()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Location parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Location) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required double elng = 1;
      private double elng_ ;
      /**
       * <code>required double elng = 1;</code>
       */
      public boolean hasElng() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required double elng = 1;</code>
       */
      public double getElng() {
        return elng_;
      }
      /**
       * <code>required double elng = 1;</code>
       */
      public Builder setElng(double value) {
        bitField0_ |= 0x00000001;
        elng_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required double elng = 1;</code>
       */
      public Builder clearElng() {
        bitField0_ = (bitField0_ & ~0x00000001);
        elng_ = 0D;
        onChanged();
        return this;
      }

      // required double elat = 2;
      private double elat_ ;
      /**
       * <code>required double elat = 2;</code>
       */
      public boolean hasElat() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required double elat = 2;</code>
       */
      public double getElat() {
        return elat_;
      }
      /**
       * <code>required double elat = 2;</code>
       */
      public Builder setElat(double value) {
        bitField0_ |= 0x00000002;
        elat_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required double elat = 2;</code>
       */
      public Builder clearElat() {
        bitField0_ = (bitField0_ & ~0x00000002);
        elat_ = 0D;
        onChanged();
        return this;
      }

      // optional string province = 3;
      private Object province_ = "";
      /**
       * <code>optional string province = 3;</code>
       */
      public boolean hasProvince() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string province = 3;</code>
       */
      public String getProvince() {
        Object ref = province_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          province_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string province = 3;</code>
       */
      public com.google.protobuf.ByteString
          getProvinceBytes() {
        Object ref = province_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          province_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string province = 3;</code>
       */
      public Builder setProvince(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        province_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string province = 3;</code>
       */
      public Builder clearProvince() {
        bitField0_ = (bitField0_ & ~0x00000004);
        province_ = getDefaultInstance().getProvince();
        onChanged();
        return this;
      }
      /**
       * <code>optional string province = 3;</code>
       */
      public Builder setProvinceBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        province_ = value;
        onChanged();
        return this;
      }

      // optional string city = 4;
      private Object city_ = "";
      /**
       * <code>optional string city = 4;</code>
       */
      public boolean hasCity() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional string city = 4;</code>
       */
      public String getCity() {
        Object ref = city_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          city_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string city = 4;</code>
       */
      public com.google.protobuf.ByteString
          getCityBytes() {
        Object ref = city_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          city_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string city = 4;</code>
       */
      public Builder setCity(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        city_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string city = 4;</code>
       */
      public Builder clearCity() {
        bitField0_ = (bitField0_ & ~0x00000008);
        city_ = getDefaultInstance().getCity();
        onChanged();
        return this;
      }
      /**
       * <code>optional string city = 4;</code>
       */
      public Builder setCityBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000008;
        city_ = value;
        onChanged();
        return this;
      }

      // optional string area = 5;
      private Object area_ = "";
      /**
       * <code>optional string area = 5;</code>
       */
      public boolean hasArea() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional string area = 5;</code>
       */
      public String getArea() {
        Object ref = area_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          area_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>optional string area = 5;</code>
       */
      public com.google.protobuf.ByteString
          getAreaBytes() {
        Object ref = area_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          area_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string area = 5;</code>
       */
      public Builder setArea(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        area_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string area = 5;</code>
       */
      public Builder clearArea() {
        bitField0_ = (bitField0_ & ~0x00000010);
        area_ = getDefaultInstance().getArea();
        onChanged();
        return this;
      }
      /**
       * <code>optional string area = 5;</code>
       */
      public Builder setAreaBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000010;
        area_ = value;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:Location)
    }

    static {
      defaultInstance = new Location(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:Location)
  }

  /**
   * Protobuf service {@code LocationService}
   */
  public static abstract class LocationService
      implements com.google.protobuf.Service {
    protected LocationService() {}

    public interface Interface {
      /**
       * <code>rpc getRealLocation(.Location) returns (.Location);</code>
       */
      public abstract void getRealLocation(
              com.google.protobuf.RpcController controller,
              Location request,
              com.google.protobuf.RpcCallback<Location> done);

    }

    public static com.google.protobuf.Service newReflectiveService(
        final Interface impl) {
      return new LocationService() {
        @Override
        public  void getRealLocation(
            com.google.protobuf.RpcController controller,
            Location request,
            com.google.protobuf.RpcCallback<Location> done) {
          impl.getRealLocation(controller, request, done);
        }

      };
    }

    public static com.google.protobuf.BlockingService
        newReflectiveBlockingService(final BlockingInterface impl) {
      return new com.google.protobuf.BlockingService() {
        public final com.google.protobuf.Descriptors.ServiceDescriptor
            getDescriptorForType() {
          return getDescriptor();
        }

        public final com.google.protobuf.Message callBlockingMethod(
            com.google.protobuf.Descriptors.MethodDescriptor method,
            com.google.protobuf.RpcController controller,
            com.google.protobuf.Message request)
            throws com.google.protobuf.ServiceException {
          if (method.getService() != getDescriptor()) {
            throw new IllegalArgumentException(
              "Service.callBlockingMethod() given method descriptor for " +
              "wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return impl.getRealLocation(controller, (Location)request);
            default:
              throw new AssertionError("Can't get here.");
          }
        }

        public final com.google.protobuf.Message
            getRequestPrototype(
            com.google.protobuf.Descriptors.MethodDescriptor method) {
          if (method.getService() != getDescriptor()) {
            throw new IllegalArgumentException(
              "Service.getRequestPrototype() given method " +
              "descriptor for wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return Location.getDefaultInstance();
            default:
              throw new AssertionError("Can't get here.");
          }
        }

        public final com.google.protobuf.Message
            getResponsePrototype(
            com.google.protobuf.Descriptors.MethodDescriptor method) {
          if (method.getService() != getDescriptor()) {
            throw new IllegalArgumentException(
              "Service.getResponsePrototype() given method " +
              "descriptor for wrong service type.");
          }
          switch(method.getIndex()) {
            case 0:
              return Location.getDefaultInstance();
            default:
              throw new AssertionError("Can't get here.");
          }
        }

      };
    }

    /**
     * <code>rpc getRealLocation(.Location) returns (.Location);</code>
     */
    public abstract void getRealLocation(
        com.google.protobuf.RpcController controller,
        Location request,
        com.google.protobuf.RpcCallback<Location> done);

    public static final
        com.google.protobuf.Descriptors.ServiceDescriptor
        getDescriptor() {
      return LocationBean.getDescriptor().getServices().get(0);
    }
    public final com.google.protobuf.Descriptors.ServiceDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }

    public final void callMethod(
        com.google.protobuf.Descriptors.MethodDescriptor method,
        com.google.protobuf.RpcController controller,
        com.google.protobuf.Message request,
        com.google.protobuf.RpcCallback<
          com.google.protobuf.Message> done) {
      if (method.getService() != getDescriptor()) {
        throw new IllegalArgumentException(
          "Service.callMethod() given method descriptor for wrong " +
          "service type.");
      }
      switch(method.getIndex()) {
        case 0:
          this.getRealLocation(controller, (Location)request,
            com.google.protobuf.RpcUtil.<Location>specializeCallback(
              done));
          return;
        default:
          throw new AssertionError("Can't get here.");
      }
    }

    public final com.google.protobuf.Message
        getRequestPrototype(
        com.google.protobuf.Descriptors.MethodDescriptor method) {
      if (method.getService() != getDescriptor()) {
        throw new IllegalArgumentException(
          "Service.getRequestPrototype() given method " +
          "descriptor for wrong service type.");
      }
      switch(method.getIndex()) {
        case 0:
          return Location.getDefaultInstance();
        default:
          throw new AssertionError("Can't get here.");
      }
    }

    public final com.google.protobuf.Message
        getResponsePrototype(
        com.google.protobuf.Descriptors.MethodDescriptor method) {
      if (method.getService() != getDescriptor()) {
        throw new IllegalArgumentException(
          "Service.getResponsePrototype() given method " +
          "descriptor for wrong service type.");
      }
      switch(method.getIndex()) {
        case 0:
          return Location.getDefaultInstance();
        default:
          throw new AssertionError("Can't get here.");
      }
    }

    public static Stub newStub(
        com.google.protobuf.RpcChannel channel) {
      return new Stub(channel);
    }

    public static final class Stub extends LocationService implements Interface {
      private Stub(com.google.protobuf.RpcChannel channel) {
        this.channel = channel;
      }

      private final com.google.protobuf.RpcChannel channel;

      public com.google.protobuf.RpcChannel getChannel() {
        return channel;
      }

      public  void getRealLocation(
          com.google.protobuf.RpcController controller,
          Location request,
          com.google.protobuf.RpcCallback<Location> done) {
        channel.callMethod(
          getDescriptor().getMethods().get(0),
          controller,
          request,
          Location.getDefaultInstance(),
          com.google.protobuf.RpcUtil.generalizeCallback(
            done,
            Location.class,
            Location.getDefaultInstance()));
      }
    }

    public static BlockingInterface newBlockingStub(
        com.google.protobuf.BlockingRpcChannel channel) {
      return new BlockingStub(channel);
    }

    public interface BlockingInterface {
      public Location getRealLocation(
              com.google.protobuf.RpcController controller,
              Location request)
          throws com.google.protobuf.ServiceException;
    }

    private static final class BlockingStub implements BlockingInterface {
      private BlockingStub(com.google.protobuf.BlockingRpcChannel channel) {
        this.channel = channel;
      }

      private final com.google.protobuf.BlockingRpcChannel channel;

      public Location getRealLocation(
          com.google.protobuf.RpcController controller,
          Location request)
          throws com.google.protobuf.ServiceException {
        return (Location) channel.callBlockingMethod(
          getDescriptor().getMethods().get(0),
          controller,
          request,
          Location.getDefaultInstance());
      }

    }

    // @@protoc_insertion_point(class_scope:LocationService)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_Location_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_Location_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\016Location.proto\"T\n\010Location\022\014\n\004elng\030\001 \002" +
      "(\001\022\014\n\004elat\030\002 \002(\001\022\020\n\010province\030\003 \001(\t\022\014\n\004ci" +
      "ty\030\004 \001(\t\022\014\n\004area\030\005 \001(\t2:\n\017LocationServic" +
      "e\022\'\n\017getRealLocation\022\t.Location\032\t.Locati" +
      "onB$\n\021com.tiza.rpc.beanB\014LocationBean\210\001\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_Location_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_Location_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_Location_descriptor,
              new String[] { "Elng", "Elat", "Province", "City", "Area", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
